/**
 * Build configuration of the plugin.
 *
 * A plugin is an ES library with up to four entry points. Each one runs in a different place:
 *
 * | Entry     | File                    | Runs in                                   | Imported by                         |
 * |-----------|-------------------------|-------------------------------------------|-------------------------------------|
 * | `index`   | src/index.ts            | The Luna Park editor (browser)            | The editor (`import(target)`)       |
 * | `runtime` | src/entries/runtime.ts  | The generated **frontend** (browser)      | Code generated by your nodes/comps  |
 * | `server`  | src/entries/server.ts   | The generated **backend** (Node, Fastify) | Code generated by backend nodes     |
 * | `shared`  | src/entries/shared.ts   | Both frontend and backend                 | Code generated by shared nodes      |
 *
 * Only `index` is required. Delete the other entries (here and in package.json "exports") if you
 * don't generate code that imports them.
 *
 * See docs/14-packaging.md.
 */
import vue from "@vitejs/plugin-vue";
import path from "path";
import type { UserConfig } from "vite";
import { defineConfig } from "vite";
import cssInjectedByJsPlugin from "vite-plugin-css-injected-by-js";

import packageDefinition from "./package.json" with { type: "json" };

/**
 * Entries whose bundle receives the plugin CSS.
 * `index` is for the editor. `runtime` is for the generated app, because components exported from
 * the runtime keep their scoped styles. `server` and `shared` may run in Node, which has no `document`.
 */
const cssEntries = new Set(["index.js", "runtime.js"]);

export default defineConfig(() => {
    const config: UserConfig = {
        build: {
            lib: {
                entry: {
                    index: "src/index.ts",
                    runtime: "src/entries/runtime.ts",
                    server: "src/entries/server.ts",
                    shared: "src/entries/shared.ts"
                },
                formats: ["es"],
                name: packageDefinition.name
            },
            rolldownOptions: {
                /*
                 * Peer dependencies are provided by the host (the editor, or the generated app's
                 * package.json), so they must not be bundled. The editor provides `vue`, `vue-router`
                 * and `@luna-park/design`.
                 * Node-only libraries used by the server entry (e.g. "nodemailer") should also be
                 * listed here and declared in `build.backImports`, so the generated backend installs them.
                 */
                external: [...Object.keys(packageDefinition.peerDependencies || {})]
            }
        },
        plugins: [
            vue(),
            cssInjectedByJsPlugin({ jsAssetsFilterFunction: (chunk) => cssEntries.has(chunk.fileName) })
        ],
        preview: {
            allowedHosts: [
                "localhost",
                "127.0.0.1",
                "https://luna-park.app"
            ],
            host: "127.0.0.1",
            port: 2084
        },
        resolve: {
            alias: {
                "@": path.resolve(import.meta.dirname, "src")
            }
        }
    };

    return config;
});
